import { jsPDF } from 'jspdf';
import { getCompanySettings } from '../pages/SettingsPage';

function fmtDate(dateStr: string | null | undefined): string {
  if (!dateStr) return '—';
  const d = new Date(dateStr);
  if (isNaN(d.getTime())) return '—';
  const dd = String(d.getDate()).padStart(2, '0');
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const yyyy = d.getFullYear();
  return `${dd}/${mm}/${yyyy}`;
}

export async function generateInvoicePdfBase64(invoice: any, lang: 'en' | 'nl' = 'en'): Promise<string> {
  const doc = new jsPDF();
  const trip = invoice.trip || {};
  const co = getCompanySettings();

  function safeText(str: string | null | undefined): string {
    if (!str) return '';
    return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^\x20-\x7E]/g, '');
  }

  const dict = {
    en: {
      invoice: 'INVOICE',
      invoiceNo: 'Invoice No:',
      tripRef: 'Trip Ref:',
      issueDate: 'Issue Date:',
      dueDate: 'Due Date:',
      from: 'FROM:',
      toClient: 'TO / CLIENT:',
      description: 'Description of Services',
      vat: 'VAT',
      qty: 'Qty',
      amount: 'Amount (EUR)',
      serviceName: 'Road freight transport services',
      route: 'Route:',
      dates: 'Loading/Unloading:',
      cargo: 'Cargo:',
      pallets: 'Pallets',
      vehicle: 'Vehicle:',
      driver: 'Driver:',
      refs: 'Refs: Loading',
      unloading: 'Unloading',
      subtotal: 'Subtotal:',
      total: 'TOTAL:',
      notes: 'Notes:',
      footer1: 'Thank you for your business!',
      footer2: 'Invoice automatically generated by HapCargo SaaS',
      taxId: 'Tax ID',
      regNo: 'Reg No',
      phone: 'Phone',
      email: 'Email',
      bank: 'Bank',
      iban: 'IBAN',
      vatId: 'VAT / Tax ID',
      paymentTerms: 'Payment Terms:',
      address: 'Address'
    },
    nl: {
      invoice: 'FACTUUR',
      invoiceNo: 'Factuurnummer:',
      tripRef: 'Rit Ref:',
      issueDate: 'Factuurdatum:',
      dueDate: 'Vervaldatum:',
      from: 'VAN:',
      toClient: 'AAN / KLANT:',
      description: 'Omschrijving van diensten',
      vat: 'BTW',
      qty: 'Aantal',
      amount: 'Bedrag (EUR)',
      serviceName: 'Wegtransportdiensten',
      route: 'Route:',
      dates: 'Laden/Lossen:',
      cargo: 'Lading:',
      pallets: 'Pallets',
      vehicle: 'Voertuig:',
      driver: 'Chauffeur:',
      refs: 'Ref: Laden',
      unloading: 'Lossen',
      subtotal: 'Subtotaal:',
      total: 'TOTAAL:',
      notes: 'Notities:',
      footer1: 'Bedankt voor uw zaken!',
      footer2: 'Factuur automatisch gegenereerd door HapCargo SaaS',
      taxId: 'KVK / BTW',
      regNo: 'KVK',
      phone: 'Tel',
      email: 'E-mail',
      bank: 'Bank',
      iban: 'IBAN',
      vatId: 'BTW / Tax ID',
      paymentTerms: 'Betalingsvoorwaarden:',
      address: 'Adres'
    },
    ro: {
      invoice: 'FACTURĂ',
      invoiceNo: 'Nr. Factură:',
      tripRef: 'Ref. Cursă:',
      issueDate: 'Data emiterii:',
      dueDate: 'Scadență:',
      from: 'FURNIZOR:',
      toClient: 'CLIENT:',
      description: 'Descrierea serviciilor',
      vat: 'TVA',
      qty: 'Cant.',
      amount: 'Suma (EUR)',
      serviceName: 'Servicii de transport rutier de marfă',
      route: 'Ruta:',
      dates: 'Încărcare/Descărcare:',
      cargo: 'Marfă:',
      pallets: 'Palți',
      vehicle: 'Vehicul:',
      driver: 'Șofer:',
      refs: 'Ref: Încărcare',
      unloading: 'Descărcare',
      subtotal: 'Subtotal:',
      total: 'TOTAL:',
      notes: 'Note:',
      footer1: 'Vă mulțumim pentru colaborare!',
      footer2: 'Factură generată automat prin HapCargo SaaS',
      taxId: 'CUI',
      regNo: 'Reg. Com.',
      phone: 'Tel',
      email: 'Email',
      bank: 'Banca',
      iban: 'IBAN',
      vatId: 'CUI / CIF',
      paymentTerms: 'Termen de plată:',
      address: 'Adresa'
    },
    de: {
      invoice: 'RECHNUNG',
      invoiceNo: 'Rechnungs-Nr:',
      tripRef: 'Fahrt Ref:',
      issueDate: 'Rechnungsdatum:',
      dueDate: 'Fälligkeitsdatum:',
      from: 'VON:',
      toClient: 'KUNDE:',
      description: 'Beschreibung der Leistungen',
      vat: 'MwSt.',
      qty: 'Menge',
      amount: 'Betrag (EUR)',
      serviceName: 'Straßengüterverkehr',
      route: 'Route:',
      dates: 'Laden/Entladen:',
      cargo: 'Fracht:',
      pallets: 'Paletten',
      vehicle: 'Fahrzeug:',
      driver: 'Fahrer:',
      refs: 'Ref: Laden',
      unloading: 'Entladen',
      subtotal: 'Zwischensumme:',
      total: 'GESAMT:',
      notes: 'Notizen:',
      footer1: 'Vielen Dank für Ihre Zusammenarbeit!',
      footer2: 'Rechnung automatisch generiert durch HapCargo SaaS',
      taxId: 'Steuer-Nr.',
      regNo: 'Reg-Nr.',
      phone: 'Tel',
      email: 'E-Mail',
      bank: 'Bank',
      iban: 'IBAN',
      vatId: 'USt-IdNr.',
      paymentTerms: 'Zahlungsbedingungen:',
      address: 'Adresse'
    },
    fr: {
      invoice: 'FACTURE',
      invoiceNo: 'N° Facture:',
      tripRef: 'Réf. Trajet:',
      issueDate: 'Date d\'émission:',
      dueDate: 'Date d\'échéance:',
      from: 'DE:',
      toClient: 'À / CLIENT:',
      description: 'Description des services',
      vat: 'TVA',
      qty: 'Qté',
      amount: 'Montant (EUR)',
      serviceName: 'Services de transport routier de fret',
      route: 'Itinéraire:',
      dates: 'Chargement/Déchargement:',
      cargo: 'Marchandise:',
      pallets: 'Palettes',
      vehicle: 'Véhicule:',
      driver: 'Chauffeur:',
      refs: 'Réf: Chargement',
      unloading: 'Déchargement',
      subtotal: 'Sous-total:',
      total: 'TOTAL:',
      notes: 'Notes:',
      footer1: 'Merci pour votre confiance !',
      footer2: 'Facture générée automatiquement par HapCargo SaaS',
      taxId: 'N° TVA',
      regNo: 'N° Reg',
      phone: 'Tél',
      email: 'Email',
      bank: 'Banque',
      iban: 'IBAN',
      vatId: 'TVA Intracommunautaire',
      paymentTerms: 'Conditions de paiement:',
      address: 'Adresse'
    }
  };
  const t = dict[lang] || dict['en'];

  // Determine company display values (fall back to defaults if empty)
  const coName    = safeText(co.name    || 'HapCargo Transport S.R.L.');
  const coCui     = safeText(co.cui     || 'RO12345678');
  const coRegNo   = safeText(co.regNo   || 'J40/1234/2024');
  const coAddress = safeText([co.address, co.postalCode, co.city, co.country].filter(Boolean).join(', ') || 'Bucuresti, Romania');
  const coPhone   = safeText(co.phone   || '+40 7xx xxx xxx');
  const coEmail   = safeText(co.email   || 'office@hapcargo.ro');
  const coBank    = co.bank    ? safeText(co.bank) : '';
  const coIban    = co.iban    ? safeText(co.iban) : '';

  // ─── 1. LOGO / BRAND ────────────────────────────────────────────────
  let headerY = 18;

  if (co.logo) {
    try {
      await new Promise<void>((resolve, reject) => {
        const img = new Image();
        img.crossOrigin = 'Anonymous';
        img.onload = () => {
          const canvas = document.createElement('canvas');
          canvas.width = img.width;
          canvas.height = img.height;
          const ctx = canvas.getContext('2d');
          if (ctx) {
            ctx.drawImage(img, 0, 0);
            const jpegData = canvas.toDataURL('image/jpeg', 0.9);
            // aspect ratio logic
            const maxW = 100;
            const maxH = 38;
            const ratio = Math.min(maxW / img.width, maxH / img.height);
            const finalLogoHeight = img.height * ratio;
            doc.addImage(jpegData, 'JPEG', 14, 10, img.width * ratio, finalLogoHeight);
            headerY = Math.max(30, 10 + finalLogoHeight + 4);
          }
          resolve();
        };
        img.onerror = () => reject(new Error('Failed to load logo'));
        img.src = co.logo;
      });
    } catch {
      // Fall back to text brand if logo fails
      doc.setFontSize(22);
      doc.setTextColor(249, 115, 22);
      doc.setFont('helvetica', 'bold');
      doc.text(coName, 14, 18);
    }
  } else {
    doc.setFontSize(22);
    doc.setTextColor(249, 115, 22);
    doc.setFont('helvetica', 'bold');
    doc.text(coName, 14, 18);
  }

  // Title
  const invoiceTitleY = headerY + 8;
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.text(t.invoice, 14, invoiceTitleY);

  // ─── 2. INVOICE META (right) ─────────────────────────────────────────
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  doc.text(`${t.invoiceNo} ${safeText(invoice.invoiceNumber)}`, 145, 18);
  doc.text(`${t.issueDate} ${fmtDate(invoice.issueDate)}`, 145, 24);
  doc.text(`${t.dueDate}   ${fmtDate(invoice.dueDate)}`, 145, 30);
  
  // calculate payment terms
  let termsStr = '30 days';
  if (invoice.issueDate && invoice.dueDate) {
    const diffTime = Math.abs(new Date(invoice.dueDate).getTime() - new Date(invoice.issueDate).getTime());
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
    termsStr = `${diffDays} days`;
  }
  doc.text(`${t.paymentTerms} ${termsStr}`, 145, 36);

  if (invoice.trip && invoice.trip.referenceNumber) {
    doc.text(`${t.tripRef} ${safeText(invoice.trip.referenceNumber)}`, 145, 42);
  }

  // Decorative separator
  const lineY = Math.max(invoiceTitleY + 4, invoice.trip?.referenceNumber ? 46 : 40);
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(14, lineY, 196, lineY);

  // ─── 3. FROM / TO ────────────────────────────────────────────────────
  const addrY = lineY + 8;

  // FROM (left)
  doc.setFontSize(9.5);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.text(t.from, 14, addrY);

  doc.setFontSize(9.5);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  const fromNameLines = doc.splitTextToSize(coName, 80);
  doc.text(fromNameLines, 14, addrY + 5);
  const fromNameHeight = fromNameLines.length * 4.5;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 51, 51);
  let fromContent = [
    `${t.taxId}: ${coCui}`,
    coRegNo ? `${t.regNo}: ${coRegNo}` : null,
    coAddress,
    coPhone ? `${t.phone}: ${coPhone}` : null,
    coEmail ? `${t.email}: ${coEmail}` : null,
    coBank ? `${t.bank}: ${coBank}` : null,
    coIban ? `${t.iban}: ${coIban}` : null,
  ].filter(Boolean).join('\n');
  const fromLinesSplit = doc.splitTextToSize(fromContent, 85);
  doc.text(fromLinesSplit, 14, addrY + 5 + fromNameHeight);

  // TO (right)
  doc.setFontSize(9.5);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.text(t.toClient, 110, addrY);

  doc.setFontSize(9.5);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  const clientNameLines = doc.splitTextToSize(safeText(invoice.client?.name || 'Client'), 80);
  doc.text(clientNameLines, 110, addrY + 5);
  const clientNameHeight = clientNameLines.length * 4.5;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 51, 51);
  const clientAddrRaw = [
    invoice.client?.address,
    invoice.client?.postalCode,
    invoice.client?.country,
  ].filter(Boolean).join(', ') || '—';
  
  let toContent = [
    `${t.vatId}: ${safeText(invoice.client?.cui || '—')}`,
    `${t.address}: ${safeText(clientAddrRaw)}`,
    `${t.email}: ${safeText(invoice.client?.contactEmail || '—')}`,
    `${t.phone}: ${safeText(invoice.client?.phone || '—')}`,
  ].join('\n');
  const toLinesSplit = doc.splitTextToSize(toContent, 85);
  doc.text(toLinesSplit, 110, addrY + 5 + clientNameHeight);

  // Calculate table Y based on address heights
  const tableY = Math.max(addrY + 10 + fromNameHeight + fromLinesSplit.length * 4.5, addrY + 10 + clientNameHeight + toLinesSplit.length * 4.5) + 8;

  // ─── 4. SERVICES TABLE ───────────────────────────────────────────────
  doc.setFillColor(241, 245, 249);
  doc.rect(14, tableY, 182, 8, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text(t.description, 16, tableY + 5.5);
  doc.text(t.qty, 130, tableY + 5.5);
  doc.text(t.amount, 163, tableY + 5.5);

  let currentItemY = tableY + 14;
  
  const baseAmount = Number(invoice.amount) || 0;
  let itemsSubtotal = 0;

  if (invoice.vatType === 'REVERSE_CHARGE') {
    vatLabel = 'VAT 0% (Reverse Charge)';
    vatAmt = 0;
  } else if (invoice.vatType === 'EXEMPT') {
    vatLabel = 'VAT 0% (Exempt)';
    vatAmt = 0;
  }
  
  const finalTotal = subtotal + vatAmt;

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(51, 51, 51);
  doc.text(t.subtotal, 140, totalsY);
  doc.setFont('helvetica', 'normal');
  doc.text(`EUR ${Number(subtotal).toFixed(2)}`, 170, totalsY);

  doc.setFont('helvetica', 'bold');
  doc.text(vatLabel, 140, totalsY + 6);
  doc.setFont('helvetica', 'normal');
  doc.text(`EUR ${Number(vatAmt).toFixed(2)}`, 170, totalsY + 6);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text(t.total, 140, totalsY + 14);
  doc.text(`EUR ${Number(finalTotal).toFixed(2)}`, 170, totalsY + 14);

  // ─── 7. NOTES ────────────────────────────────────────────────────────
  const notesY = Math.max(afterDetailsY + 10, totalsY + 30);
  if (invoice.notes) {
    doc.setFontSize(9.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text(t.notes, 14, notesY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 51, 51);
    const notesStr = safeText(invoice.notes);
    const splitNotes = doc.splitTextToSize(notesStr, 180);
    doc.text(splitNotes, 14, notesY + 5);
  }

  // ─── 8. FOOTER ───────────────────────────────────────────────────────
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(t.footer1, 14, 280);

  return doc.output('datauristring');
}
