import { jsPDF } from 'jspdf';
import { getCompanySettings } from '../pages/SettingsPage';

function fmtDate(dateStr: string | null | undefined): string {
  if (!dateStr) return '—';
  const d = new Date(dateStr);
  if (isNaN(d.getTime())) return '—';
  const dd = String(d.getDate()).padStart(2, '0');
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const yyyy = d.getFullYear();
  return `${dd}/${mm}/${yyyy}`;
}

export function generateInvoicePdfBase64(invoice: any, lang: 'en' | 'nl' = 'en') {
  const doc = new jsPDF();
  const trip = invoice.trip || {};
  const co = getCompanySettings();

  function safeText(str: string | null | undefined): string {
    if (!str) return '';
    return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^\x20-\x7E]/g, '');
  }

  const dict = {
    en: {
      invoice: 'INVOICE',
      invoiceNo: 'Invoice No:',
      issueDate: 'Issue Date:',
      dueDate: 'Due Date:',
      from: 'FROM:',
      toClient: 'TO / CLIENT:',
      description: 'Description of Services',
      vat: 'VAT',
      qty: 'Qty',
      amount: 'Amount (EUR)',
      serviceName: 'Road freight transport services',
      route: 'Route:',
      dates: 'Loading/Unloading:',
      cargo: 'Cargo:',
      pallets: 'Pallets',
      vehicle: 'Vehicle:',
      driver: 'Driver:',
      refs: 'Refs: Loading',
      unloading: 'Unloading',
      subtotal: 'Subtotal:',
      total: 'TOTAL:',
      notes: 'Notes:',
      footer1: 'Thank you for your business!',
      footer2: 'Invoice automatically generated by HapTrans SaaS'
    },
    nl: {
      invoice: 'FACTUUR',
      invoiceNo: 'Factuurnummer:',
      issueDate: 'Factuurdatum:',
      dueDate: 'Vervaldatum:',
      from: 'VAN:',
      toClient: 'AAN / KLANT:',
      description: 'Omschrijving van diensten',
      vat: 'BTW',
      qty: 'Aantal',
      amount: 'Bedrag (EUR)',
      serviceName: 'Wegtransportdiensten',
      route: 'Route:',
      dates: 'Laden/Lossen:',
      cargo: 'Lading:',
      pallets: 'Pallets',
      vehicle: 'Voertuig:',
      driver: 'Chauffeur:',
      refs: 'Ref: Laden',
      unloading: 'Lossen',
      subtotal: 'Subtotaal:',
      total: 'TOTAAL:',
      notes: 'Notities:',
      footer1: 'Bedankt voor uw zaken!',
      footer2: 'Factuur automatisch gegenereerd door HapTrans SaaS'
    }
  };
  const t = dict[lang] || dict['en'];

  // Determine company display values (fall back to defaults if empty)
  const coName    = safeText(co.name    || 'HapTrans Transport S.R.L.');
  const coCui     = safeText(co.cui     || 'RO12345678');
  const coRegNo   = safeText(co.regNo   || 'J40/1234/2024');
  const coAddress = safeText([co.address, co.postalCode, co.city, co.country].filter(Boolean).join(', ') || 'Bucuresti, Romania');
  const coPhone   = safeText(co.phone   || '+40 7xx xxx xxx');
  const coEmail   = safeText(co.email   || 'office@haptrans.ro');
  const coBank    = co.bank    ? safeText(`Banca: ${co.bank}`) : '';
  const coIban    = co.iban    ? safeText(`IBAN: ${co.iban}`) : '';

  // ─── 1. LOGO / BRAND ────────────────────────────────────────────────
  let headerY = 18;

  if (co.logo) {
    try {
      // Detect image type from data URL
      const ext = co.logo.startsWith('data:image/png') ? 'PNG'
        : co.logo.startsWith('data:image/svg') ? 'SVG'
        : 'JPEG';
      doc.addImage(co.logo, ext, 14, 10, 40, 14);
      headerY = 30;
    } catch {
      // Fall back to text brand if logo fails
      doc.setFontSize(22);
      doc.setTextColor(249, 115, 22);
      doc.setFont('helvetica', 'bold');
      doc.text(coName, 14, 18);
    }
  } else {
    doc.setFontSize(22);
    doc.setTextColor(249, 115, 22);
    doc.setFont('helvetica', 'bold');
    doc.text(coName, 14, 18);
  }

  // Title
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.text(t.invoice, 14, headerY + 12);

  // ─── 2. INVOICE META (right) ─────────────────────────────────────────
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'normal');
  doc.text(`${t.invoiceNo} ${safeText(invoice.invoiceNumber)}`, 145, 18);
  doc.text(`${t.issueDate} ${fmtDate(invoice.issueDate)}`, 145, 24);
  doc.text(`${t.dueDate}   ${fmtDate(invoice.dueDate)}`, 145, 30);

  // Decorative separator
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(14, 38, 196, 38);

  // ─── 3. FROM / TO ────────────────────────────────────────────────────
  const addrY = 46;

  // FROM (left)
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.setFont('helvetica', 'bold');
  doc.text(t.from, 14, addrY);

  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  const fromNameLines = doc.splitTextToSize(coName, 80);
  doc.text(fromNameLines, 14, addrY + 5);
  const fromNameHeight = fromNameLines.length * 4.5;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  let fromContent = [
    `CUI / Tax ID: ${coCui}`,
    coRegNo ? `Reg No: ${coRegNo}` : null,
    coAddress,
    coPhone ? `Tel: ${coPhone}` : null,
    coEmail ? `Email: ${coEmail}` : null,
    coBank || null,
    coIban || null,
  ].filter(Boolean).join('\n');
  const fromLinesSplit = doc.splitTextToSize(fromContent, 85);
  doc.text(fromLinesSplit, 14, addrY + 2 + fromNameHeight);

  // TO (right)
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.setFont('helvetica', 'bold');
  doc.text(t.toClient, 110, addrY);

  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  const clientNameLines = doc.splitTextToSize(safeText(invoice.client?.name || 'Client'), 80);
  doc.text(clientNameLines, 110, addrY + 5);
  const clientNameHeight = clientNameLines.length * 4.5;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  const clientAddrRaw = [
    invoice.client?.address,
    invoice.client?.postalCode,
    invoice.client?.country,
  ].filter(Boolean).join(', ') || '—';
  
  let toContent = [
    `VAT / Tax ID: ${safeText(invoice.client?.cui || '—')}`,
    `Address: ${safeText(clientAddrRaw)}`,
    `Email: ${safeText(invoice.client?.contactEmail || '—')}`,
    `Phone: ${safeText(invoice.client?.phone || '—')}`,
  ].join('\n');
  const toLinesSplit = doc.splitTextToSize(toContent, 85);
  doc.text(toLinesSplit, 110, addrY + 2 + clientNameHeight);

  // Calculate table Y based on address heights
  const tableY = Math.max(addrY + 10 + fromLinesSplit.length * 4.5, addrY + 10 + toLinesSplit.length * 4.5) + 8;

  // ─── 4. SERVICES TABLE ───────────────────────────────────────────────
  doc.setFillColor(241, 245, 249);
  doc.rect(14, tableY, 182, 8, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text(t.description, 16, tableY + 5.5);
  doc.text(t.vat, 115, tableY + 5.5);
  doc.text(t.qty, 142, tableY + 5.5);
  doc.text(t.amount, 163, tableY + 5.5);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text(t.serviceName, 16, tableY + 14);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(`${invoice.vatPercent}%`, 115, tableY + 14);
  doc.text('1', 142, tableY + 14);
  doc.text(`EUR ${Number(invoice.amount).toFixed(2)}`, 163, tableY + 14);

  // ─── 5. TRIP DETAILS ────────────────────────────────────────────────
  const detailY = tableY + 20;
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);

  const pickupDateFmt  = fmtDate(trip.pickupDate);
  const dropoffDateFmt = fmtDate(trip.dropoffDate);

  const routeText   = `${t.route} ${safeText(trip.pickupAddress || '—')} - ${safeText(trip.dropoffAddress || '—')}`;
  const datesText   = `${t.dates} ${pickupDateFmt}${trip.pickupTime ? ' at ' + trip.pickupTime : ''} - ${dropoffDateFmt}${trip.dropoffTime ? ' at ' + trip.dropoffTime : ''}`;
  
  const palletTypeStr = trip.palletType ? ` (${safeText(trip.palletType)})` : '';
  const cargoText   = `${t.cargo} ${trip.pallets || '0'} ${t.pallets}${palletTypeStr}  |  ${trip.weightKg || '0'} kg  |  ${trip.volumeCbm || '0'} m³`;
  const vehicleText = `${t.vehicle} ${safeText(trip.truck?.plateNumber || '—')}  |  ${t.driver} ${safeText(trip.driver?.user?.name || '—')}`;
  const refsText    = `${t.refs} ${safeText(trip.loadingReference || '—')}  |  ${t.unloading} ${safeText(trip.unloadingReference || '—')}`;

  const wrappedRoute = doc.splitTextToSize(`• ${routeText}`, 175);
  doc.text(wrappedRoute, 18, detailY);
  const nextY = detailY + wrappedRoute.length * 4;

  doc.text(`• ${datesText}`,   18, nextY + 1);
  doc.text(`• ${cargoText}`,   18, nextY + 6);
  doc.text(`• ${vehicleText}`, 18, nextY + 11);
  doc.text(`• ${refsText}`,    18, nextY + 16);

  const afterDetailsY = nextY + 22;

  doc.setDrawColor(203, 213, 225);
  doc.setLineWidth(0.5);
  doc.line(14, afterDetailsY, 196, afterDetailsY);

  // ─── 6. TOTALS ───────────────────────────────────────────────────────
  const subtotal  = Number(invoice.amount);
  const vatAmount = (subtotal * Number(invoice.vatPercent)) / 100;
  const total     = subtotal + vatAmount;

  const calcY = afterDetailsY + 8;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(t.subtotal, 120, calcY);
  doc.text(`EUR ${subtotal.toFixed(2)}`, 165, calcY);

  doc.text(`${t.vat} (${invoice.vatPercent}%):`, 120, calcY + 6);
  doc.text(`EUR ${vatAmount.toFixed(2)}`, 165, calcY + 6);

  doc.setLineWidth(1.0);
  doc.setDrawColor(15, 23, 42);
  doc.line(120, calcY + 10, 196, calcY + 10);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(11);
  doc.text(t.total, 120, calcY + 16);
  doc.text(`EUR ${total.toFixed(2)}`, 165, calcY + 16);

  // ─── 7. NOTES ────────────────────────────────────────────────────────
  const notesY = calcY + 30;
  if (invoice.notes || trip.notes) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text(t.notes, 14, notesY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    const notesStr = safeText(invoice.notes || trip.notes);
    const splitNotes = doc.splitTextToSize(notesStr, 180);
    doc.text(splitNotes, 14, notesY + 5);
  }

  // ─── 8. FOOTER ───────────────────────────────────────────────────────
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(t.footer1, 14, 280);
  doc.text(t.footer2, 125, 280);

  return doc.output('datauristring');
}
