[providers.node]
nodeVersion = "20"

[phases.setup]
nixPkgs = ["...", "chromium", "nss", "freetype", "harfbuzz", "pango", "libglvnd", "glib"]
aptPkgs = []

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"
NIXPACKS_APT_PKGS = ""
