providers = ["node"]

[phases.setup]
nixPkgs = [
  "wget",
  "gnupg",
  "alsa-lib",
  "at-spi2-atk",
  "at-spi2-core",
  "atk",
  "cairo",
  "cups",
  "dbus",
  "expat",
  "fontconfig",
  "freetype",
  "glib",
  "gtk3",
  "libdrm",
  "libglvnd",
  "libxkbcommon",
  "mesa",
  "nspr",
  "nss",
  "pango",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXcursor",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXi",
  "xorg.libXrandr",
  "xorg.libXrender",
  "xorg.libxcb",
  "xorg.libxkbfile",
  "xorg.libxshmfence",
  "unzip"
]
