const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'client/src/lib/i18n.ts');
let content = fs.readFileSync(filePath, 'utf-8');

const keysToInsert = {
  en: `
      clientProfile: "Client Profile & Rates",
      generalInfoSettings: "General Info & Billing Settings",
      companyName: "Company Name",
      vatCui: "VAT / Reg. No.",
      address: "Address",
      contactName: "Contact Name",
      contactEmail: "Contact Email",
      paymentTermsDays: "Payment Terms (Days)",
      defaultFuelSurcharge: "Default Fuel Surcharge (%)",
      invoiceLanguage: "Invoice Language",
      saveSettings: "Save Settings",
      clientRatesTitle: "Client Rates / Routes",
      addRate: "Add Rate",
      editRate: "Edit Rate",
      origin: "Origin",
      destination: "Destination",
      actions: "Actions",
      noRatesDesc: "No rates defined for this client.",
      financialDetails: "Financial Details",
      rateCard: "Rate Card:",
      manualPrice: "-- Manual Price --",
      agreedPrice: "Agreed Price (€)",
      fuelSurcharge: "Fuel Surcharge (%)",
      extraCosts: "Extra Costs (€)",
      tollCosts: "Toll Costs (€)",
      tollIncluded: "Tolls Included",
      totalEstimatedCost: "Total Estimated Cost (€)",
      tabGeneral: "General Info",
      tabPortal: "Portal",
      tabRates: "Rates / Routes",
      tabInvoices: "Invoices",
      tabTrips: "Trips",
      tabDocuments: "Documents",
      addRateCard: "Add Rate",
      rateName: "Rate Name (e.g., Standard FR-DE)",
      originCity: "Origin City",
      destCity: "Destination City",
      vehicleType: "Vehicle Type",
      priceType: "Price Type",
      basePrice: "Base Price (€)",
      tollInc: "Tolls Included?",
      saveRate: "Save Rate",
      cancel: "Cancel",
      noRates: "No rates defined for this client.",`,
  nl: `
      tabPortal: "Portaal",
      tabGeneral: "Algemene Info",
      tabRates: "Tarieven / Routes",
      tabInvoices: "Facturen",
      tabTrips: "Ritten",
      tabDocuments: "Documenten",`,
  de: `
      tabPortal: "Portal",
      tabGeneral: "Allgemeine Info",
      tabRates: "Tarife / Routen",
      tabInvoices: "Rechnungen",
      tabTrips: "Fahrten",
      tabDocs: "Dokumente",
      tabDocuments: "Dokumente",`,
  fr: `
      comingSoon: "Bientôt disponible",
      viewDesc: "La vue {{tab}} sera implémentée dans la prochaine phase et directement liée aux modules principaux de {{tab}}, mais filtrée pour ce client.",
      clientProfile: "Profil du Client & Tarifs",
      generalInfoSettings: "Infos Générales & Paramètres de Facturation",
      companyName: "Nom de l'Entreprise",
      vatCui: "TVA / Numéro d'Enreg.",
      address: "Adresse",
      contactName: "Nom du Contact",
      contactEmail: "Email du Contact",
      paymentTermsDays: "Modalités de Paiement (Jours)",
      defaultFuelSurcharge: "Surcharge de Carburant par Défaut (%)",
      invoiceLanguage: "Langue de Facturation",
      saveSettings: "Enregistrer les Paramètres",
      clientRatesTitle: "Tarifs / Itinéraires du Client",
      addRate: "Ajouter un Tarif",
      editRate: "Modifier le Tarif",
      origin: "Origine",
      destination: "Destination",
      actions: "Actions",
      noRatesDesc: "Aucun tarif défini pour ce client.",
      financialDetails: "Détails Financiers",
      rateCard: "Grille Tarifaire:",
      manualPrice: "-- Prix Manuel --",
      agreedPrice: "Prix Convenu (€)",
      fuelSurcharge: "Surcharge de Carburant (%)",
      extraCosts: "Coûts Supplémentaires (€)",
      tollCosts: "Coûts de Péage (€)",
      tollIncluded: "Péages Inclus",
      totalEstimatedCost: "Coût Total Estimé (€)",
      tabGeneral: "Infos Générales",
      tabPortal: "Portail",
      tabRates: "Tarifs / Itinéraires",
      tabInvoices: "Factures",
      tabTrips: "Voyages",
      tabDocuments: "Documents",
      addRateCard: "Ajouter un Tarif",
      rateName: "Nom du Tarif (ex: Standard FR-DE)",
      originCity: "Ville d'Origine",
      destCity: "Ville de Destination",
      vehicleType: "Type de Véhicule",
      priceType: "Type de Prix",
      basePrice: "Prix de Base (€)",
      tollInc: "Péages Inclus?",
      saveRate: "Enregistrer le Tarif",
      cancel: "Annuler",
      noRates: "Aucun tarif défini pour ce client.",`,
  es: `
      comingSoon: "Próximamente",
      viewDesc: "La vista de {{tab}} se implementará en la próxima fase y estará vinculada directamente a los módulos principales de {{tab}}, pero filtrada para este cliente.",
      clientProfile: "Perfil del Cliente y Tarifas",
      generalInfoSettings: "Información General y Configuración de Facturación",
      companyName: "Nombre de la Empresa",
      vatCui: "IVA / Número de Reg.",
      address: "Dirección",
      contactName: "Nombre del Contacto",
      contactEmail: "Correo del Contacto",
      paymentTermsDays: "Condiciones de Pago (Días)",
      defaultFuelSurcharge: "Recargo por Combustible Predeterminado (%)",
      invoiceLanguage: "Idioma de la Factura",
      saveSettings: "Guardar Configuración",
      clientRatesTitle: "Tarifas / Rutas del Cliente",
      addRate: "Agregar Tarifa",
      editRate: "Editar Tarifa",
      origin: "Origen",
      destination: "Destino",
      actions: "Acciones",
      noRatesDesc: "No hay tarifas definidas para este cliente.",
      financialDetails: "Detalles Financieros",
      rateCard: "Tarjeta de Tarifas:",
      manualPrice: "-- Precio Manual --",
      agreedPrice: "Precio Acordado (€)",
      fuelSurcharge: "Recargo por Combustible (%)",
      extraCosts: "Costos Adicionales (€)",
      tollCosts: "Costos de Peaje (€)",
      tollIncluded: "Peajes Incluidos",
      totalEstimatedCost: "Costo Total Estimado (€)",
      tabGeneral: "Info General",
      tabPortal: "Portal",
      tabRates: "Tarifas / Rutas",
      tabInvoices: "Facturas",
      tabTrips: "Viajes",
      tabDocuments: "Documentos",
      addRateCard: "Agregar Tarifa",
      rateName: "Nombre de la Tarifa (ej. Estándar FR-DE)",
      originCity: "Ciudad de Origen",
      destCity: "Ciudad de Destino",
      vehicleType: "Tipo de Vehículo",
      priceType: "Tipo de Precio",
      basePrice: "Precio Base (€)",
      tollInc: "¿Peajes Incluidos?",
      saveRate: "Guardar Tarifa",
      cancel: "Cancelar",
      noRates: "No hay tarifas definidas para este cliente.",`
};

for (const [lang, trans] of Object.entries(keysToInsert)) {
  const regex = new RegExp(`(  ${lang}: \\{\\s*translation: \\{)`);
  content = content.replace(regex, `$1\n${trans}`);
}

const tabPortalRo = `
      tabPortal: "Portal",
      tabDocuments: "Documente",`;
content = content.replace(/(  ro: \{\s*translation: \{)/, `$1${tabPortalRo}`);

fs.writeFileSync(filePath, content);
console.log('Patched i18n successfully!');
