export function generateInvoiceHtml(invoice: any, co: any, lang: 'en' | 'nl'): string {
  const trip = invoice.trip || {};

  function fmtDate(dateStr: string | null | undefined): string {
    if (!dateStr) return '—';
    const d = new Date(dateStr);
    if (isNaN(d.getTime())) return '—';
    const dd = String(d.getDate()).padStart(2, '0');
    const mm = String(d.getMonth() + 1).padStart(2, '0');
    const yyyy = d.getFullYear();
    return `${dd}/${mm}/${yyyy}`;
  }

  const dict = {
    en: {
      invoice: 'INVOICE',
      invoiceNo: 'Invoice No:',
      tripRef: 'Trip Ref:',
      issueDate: 'Issue Date:',
      dueDate: 'Due Date:',
      from: 'FROM:',
      toClient: 'TO / CLIENT:',
      description: 'Description of Services',
      vat: 'VAT',
      qty: 'Qty',
      unitPrice: 'Unit Price (EUR)',
      amount: 'Amount (EUR)',
      serviceName: 'Road freight transport services',
      route: 'Route:',
      dates: 'Loading/Unloading:',
      cargo: 'Cargo:',
      pallets: 'Pallets',
      vehicle: 'Vehicle:',
      driver: 'Driver:',
      refs: 'Refs: Loading',
      unloading: 'Unloading',
      subtotal: 'Subtotal',
      total: 'TOTAL DUE',
      notes: 'Notes:',
      footer1: 'Thank you for your business!',
      footer2: 'Invoice automatically generated by HapCargo SaaS',
      taxId: 'Tax ID',
      regNo: 'Reg No',
      phone: 'Phone',
      email: 'Email',
      bank: 'Bank',
      iban: 'IBAN',
      bic: 'BIC / SWIFT',
      accHolder: 'Account Holder',
      vatId: 'VAT / Tax ID',
      paymentTerms: 'Payment Terms:',
      address: 'Address',
      pickupDate: 'Pickup date:',
      loadingRef: 'Loading reference:',
      deliveryDate: 'Delivery date:',
      unloadingRef: 'Unloading reference:',
      transportDetails: 'Transport Details',
      summary: 'Summary',
      vatInfo: 'VAT INFORMATION',
      vatInfoText: 'Thank you for your business!',
      paymentInfo: 'Payment Information',
      lateWarning: 'Please make payment within',
      lateWarningSub: 'Late payments may incur additional charges.',
      draftTitle: 'DRAFT',
      draftSub: 'This is not a final invoice.',
      workingHours: 'Opening hours'
    },
    nl: {
      invoice: 'FACTUUR',
      invoiceNo: 'Factuurnummer:',
      tripRef: 'Rit Ref:',
      issueDate: 'Factuurdatum:',
      dueDate: 'Vervaldatum:',
      from: 'VAN:',
      toClient: 'AAN / KLANT:',
      description: 'Omschrijving van diensten',
      vat: 'BTW',
      qty: 'Aantal',
      unitPrice: 'Eenheidsprijs (EUR)',
      amount: 'Bedrag (EUR)',
      serviceName: 'Wegtransportdiensten',
      route: 'Route:',
      dates: 'Laden/Lossen:',
      cargo: 'Lading:',
      pallets: 'Pallets',
      vehicle: 'Voertuig:',
      driver: 'Chauffeur:',
      refs: 'Ref: Laden',
      unloading: 'Lossen',
      subtotal: 'Subtotaal',
      total: 'TOTAAL TE BETALEN',
      notes: 'Notities:',
      footer1: 'Bedankt voor uw zaken!',
      footer2: 'Factuur automatisch gegenereerd door HapCargo SaaS',
      taxId: 'KVK / BTW',
      regNo: 'KVK',
      phone: 'Tel',
      email: 'E-mail',
      bank: 'Bank',
      iban: 'IBAN',
      bic: 'BIC / SWIFT',
      accHolder: 'Rekeninghouder',
      vatId: 'BTW / Tax ID',
      paymentTerms: 'Betalingsvoorwaarden:',
      address: 'Adres',
      pickupDate: 'Laaddatum:',
      loadingRef: 'Laadreferentie:',
      deliveryDate: 'Leverdatum:',
      unloadingRef: 'Losreferentie:',
      transportDetails: 'Transportgegevens',
      summary: 'Overzicht',
      vatInfo: 'BTW INFORMATIE',
      vatInfoText: 'Bedankt voor uw zaken!',
      paymentInfo: 'Betalingsinformatie',
      lateWarning: 'Gelieve te betalen binnen',
      lateWarningSub: 'Te late betalingen kunnen leiden tot extra kosten.',
      draftTitle: 'CONCEPT',
      draftSub: 'Dit is geen definitieve factuur.',
      workingHours: 'Openingstijden'
    }
  };
  
  const t = (dict as any)[lang] || dict['en'];

  let termsStr = '30 days';
  if (invoice.issueDate && invoice.dueDate) {
    const diffTime = Math.abs(new Date(invoice.dueDate).getTime() - new Date(invoice.issueDate).getTime());
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
    termsStr = `${diffDays} days`;
  }

  const items = invoice.items || [];
  let itemsSubtotal = 0;
  if (items.length > 0) {
    items.forEach((item: any) => {
      itemsSubtotal += Number(item.total) || ((Number(item.quantity)||1) * (Number(item.unitPrice)||0));
    });
  } else {
    itemsSubtotal = Number(invoice.amount) || 0;
  }

  let subtotal = Number(invoice.subtotal) || itemsSubtotal;
  let vatLabel = `${t.vat} ${invoice.vatPercent || 19}%`;
  let vatAmt = Number(invoice.vatAmount) || (subtotal * (invoice.vatPercent || 19)) / 100;

  if (invoice.vatType === 'REVERSE_CHARGE') {
    vatLabel = `${t.vat} 0% (Reverse Charge)`;
    vatAmt = 0;
  } else if (invoice.vatType === 'EXEMPT') {
    vatLabel = `${t.vat} 0% (Exempt)`;
    vatAmt = 0;
  }
  const finalTotal = subtotal + vatAmt;

  const cargoArr = [];
  if (trip.pallets) cargoArr.push(`${trip.pallets} pallets`);
  if (trip.weightKg) cargoArr.push(`${trip.weightKg} kg`);
  if (trip.volumeCbm) cargoArr.push(`${trip.volumeCbm} m3`);
  const cargoStr = cargoArr.join(', ');

  let itemsHtml = '';
  if (items.length > 0) {
    itemsHtml = items.map((item: any) => `
      <tr>
        <td>
          <div class="service-title">${item.description}</div>
        </td>
        <td>${Number(item.quantity) || 1}</td>
        <td>${(Number(item.unitPrice) || 0).toFixed(2)}</td>
        <td><strong>${((Number(item.quantity)||1)*(Number(item.unitPrice)||0)).toFixed(2)}</strong></td>
      </tr>
    `).join('');
  } else {
    itemsHtml = `
      <tr>
        <td>
          <div class="service-title">${t.serviceName}</div>
        </td>
        <td>1</td>
        <td>${(Number(invoice.amount)||0).toFixed(2)}</td>
        <td><strong>${(Number(invoice.amount)||0).toFixed(2)}</strong></td>
      </tr>
    `;
  }

  const logoHtml = co.logo ? 
    `<img src="${co.logo}" alt="Logo" style="height:90px; max-width: 320px; object-fit:contain;" />` : 
    `<div class="logo">
      <span class="logo-mark">#</span>
      <span class="logo-orange">${(co.name || 'HAPCARGO').substring(0, 3).toUpperCase()}</span><span class="logo-blue">${(co.name || 'HAPCARGO').substring(3).toUpperCase()}</span>
    </div>`;

  const draftHtml = invoice.status === 'draft' ? 
    `<div>
      <div class="draft-badge">${t.draftTitle}</div>
      <div class="draft-note">${t.draftSub}</div>
    </div>` : '';

  const draftInvoiceNoHtml = invoice.status === 'draft' ? 
    `<span class="draft-no">${invoice.invoiceNumber}</span>` : 
    `<span>${invoice.invoiceNumber}</span>`;

  let workingHoursStr = co.workingHours || '';
  if (workingHoursStr) {
    if (lang === 'nl') {
      workingHoursStr = workingHoursStr
        .replace(/\b(Ma|Mon|Luni|Mo|Pon)\b/gi, 'Ma')
        .replace(/\b(Fri|Vineri|Fr|Vr|Pt)\b/gi, 'Vr')
        .replace(/\b(Luni\s*-\s*Vineri)\b/gi, 'Ma - Vr')
        .replace(/\b(Mon\s*-\s*Fri)\b/gi, 'Ma - Vr')
        .replace(/\b(Ma\s*-\s*Fri)\b/gi, 'Ma - Vr');
    } else {
      // default en
      workingHoursStr = workingHoursStr
        .replace(/\b(Ma|Luni|Mo|Pon)\b/gi, 'Mon')
        .replace(/\b(Vineri|Fr|Vr|Pt)\b/gi, 'Fri')
        .replace(/\b(Luni\s*-\s*Vineri)\b/gi, 'Mon - Fri')
        .replace(/\b(Ma\s*-\s*Vr)\b/gi, 'Mon - Fri')
        .replace(/\b(Ma\s*-\s*Fri)\b/gi, 'Mon - Fri');
    }
  }

  return `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>HapCargo Invoice</title>

<style>
  * {
    box-sizing: border-box;
  }

  body {
    margin: 0;
    background: #f4f6f8;
    font-family: Arial, Helvetica, sans-serif;
    color: #071b3a;
  }

  .invoice-page {
    width: 794px;
    height: 1122px;
    max-height: 1122px;
    margin: 0 auto;
    background: #ffffff;
    padding: 16px 30px 14px;
    display: flex;
    flex-direction: column;
    overflow: hidden;
    box-sizing: border-box;
  }

  .top {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
  }

  .logo {
    font-size: 64px;
    font-weight: 900;
    letter-spacing: -2px;
  }

  .logo-mark {
    color: #ff4b00;
    font-size: 80px;
    vertical-align: middle;
    margin-right: 8px;
  }

  .logo-orange {
    color: #ff4b00;
    font-style: italic;
  }

  .logo-blue {
    color: #061a3a;
    font-style: italic;
  }

  .invoice-meta {
    border-left: 2px solid #ff4b00;
    padding-left: 18px;
    font-size: 13px;
    line-height: 1.2;
    min-width: 250px;
  }

  .invoice-meta .row {
    display: flex;
    justify-content: flex-start;
    gap: 6px;
    margin-bottom: 3px;
  }

  .invoice-meta strong {
    color: #000;
  }

  .draft-no {
    color: #ff4b00;
    font-weight: 800;
  }

  .title-row {
    margin-top: 16px;
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
  }

  h1 {
    margin: 0;
    font-size: 26px;
    letter-spacing: 1px;
    color: #061a3a;
  }

  .draft-badge {
    background: #061a3a;
    color: white;
    padding: 10px 22px;
    border-radius: 6px;
    font-weight: 800;
    font-size: 20px;
    text-align: center;
  }

  .draft-note {
    font-size: 12px;
    margin-top: 8px;
    font-style: italic;
    text-align: center;
    color: #51627c;
  }

  .divider {
    border-top: 1px solid #d6dce5;
    margin: 14px 0;
  }

  .cards {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 12px;
    margin-bottom: 12px;
  }

  .card {
    border: 1px solid #d9e0ea;
    border-radius: 6px;
    padding: 12px 14px;
    min-height: 140px;
  }

  .card-title {
    color: #ff4b00;
    font-weight: 800;
    font-size: 14px;
    margin-bottom: 8px;
    text-transform: uppercase;
  }

  .company-name {
    font-weight: 800;
    font-size: 16px;
    margin-bottom: 12px;
  }

  .info-line {
    font-size: 13px;
    line-height: 1.4;
  }

  .service-table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 8px;
    font-size: 13px;
  }

  .service-table th {
    background: #061a3a;
    color: white;
    text-align: left;
    padding: 9px 10px;
    font-size: 12px;
  }

  .service-table th:nth-child(2),
  .service-table th:nth-child(3),
  .service-table th:nth-child(4) {
    text-align: center;
  }

  .service-table td {
    border: 1px solid #e2e7ef;
    padding: 10px 10px;
    vertical-align: middle;
  }

  .service-table td:nth-child(2),
  .service-table td:nth-child(3),
  .service-table td:nth-child(4) {
    text-align: center;
  }

  .service-title {
    font-weight: 800;
    color: #071b3a;
  }

  .service-subtitle {
    color: #52627a;
    font-size: 12px;
    margin-top: 3px;
  }

  .main-bottom {
    display: grid;
    grid-template-columns: 1.1fr 0.9fr;
    gap: 12px;
    margin-top: 12px;
  }

  .section-box {
    border: 1px solid #d9e0ea;
    border-radius: 6px;
    padding: 12px;
  }

  .section-title {
    color: #ff4b00;
    font-weight: 800;
    text-transform: uppercase;
    font-size: 13px;
    margin-bottom: 8px;
  }

  .detail-row {
    display: grid;
    grid-template-columns: auto 1fr;
    gap: 8px;
    border-bottom: 1px dashed #d9e0ea;
    padding: 2px 0;
    font-size: 12px;
  }

  .detail-row:last-child {
    border-bottom: none;
  }

  .detail-label {
    font-weight: 700;
  }

  .summary {
    padding: 0;
    overflow: hidden;
  }

  .summary-header {
    background: #061a3a;
    color: white;
    padding: 10px 12px;
    font-weight: 800;
    text-transform: uppercase;
    font-size: 13px;
  }

  .summary-body {
    padding: 12px;
  }

  .summary-row {
    display: flex;
    justify-content: space-between;
    font-size: 13px;
    margin-bottom: 10px;
  }

  .summary-line {
    border-top: 1px solid #bfc8d5;
    margin: 10px 0;
  }

  .total-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-weight: 900;
    font-size: 16px;
  }

  .total-amount {
    color: #ff4b00;
    font-size: 22px;
  }

  .vat-info {
    background: #f3f6fa;
    border-radius: 8px;
    padding: 10px;
    margin-top: 14px;
    font-size: 11px;
    color: #30415d;
    line-height: 1.5;
  }

  .payment-box {
    margin-top: 12px;
    border: 1px solid #d9e0ea;
    border-radius: 6px;
    padding: 12px;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 14px;
    background: #fbfcfe;
  }

  .payment-table {
    font-size: 12px;
    line-height: 1.8;
  }

  .payment-table div {
    display: grid;
    grid-template-columns: auto 1fr;
    gap: 8px;
  }

  .payment-note {
    border-left: 1px solid #cbd3df;
    padding-left: 18px;
    font-size: 13px;
    line-height: 1.5;
    display: flex;
    align-items: center;
  }

  .footer {
    margin-top: auto;
    border-top: 1px solid #d6dce5;
    padding-top: 10px;
    text-align: center;
    font-size: 11px;
    color: #51627c;
  }

  .footer-contact {
    display: flex;
    justify-content: center;
    gap: 28px;
    margin-bottom: 8px;
  }

  .thank-you {
    font-weight: 800;
    font-style: italic;
    color: #061a3a;
  }

  @media print {
    body {
      background: white;
    }

    .invoice-page {
      margin: 0;
      width: 100%;
      min-height: auto;
      box-shadow: none;
    }
  }
</style>
</head>

<body>

<div class="invoice-page">

  <div class="top">
    ${logoHtml}

    <div class="invoice-meta">
      <div class="row"><strong>${t.invoiceNo}</strong> ${draftInvoiceNoHtml}</div>
      <div class="row"><strong>${t.issueDate}</strong> <span>${fmtDate(invoice.issueDate)}</span></div>
      <div class="row"><strong>${t.dueDate}</strong> <span>${fmtDate(invoice.dueDate)}</span></div>
      <div class="row"><strong>${t.paymentTerms}</strong> <span>${termsStr}</span></div>
      ${trip.referenceNumber ? `<div class="row"><strong>${t.tripRef}</strong> <span>${trip.referenceNumber}</span></div>` : ''}
    </div>
  </div>

  <div class="title-row">
    <h1>${t.invoice}</h1>

    ${draftHtml}
  </div>

  <div class="divider"></div>

  <div class="cards">
    <div class="card">
      <div class="card-title">${t.from}</div>
      <div class="company-name">${co.name || 'HapCargo BV'}</div>
      <div class="info-line">${t.taxId}: ${co.cui || 'NL442452452145'}</div>
      ${(co.regNumber || co.regNo) ? `<div class="info-line">${t.regNo}: ${co.regNumber || co.regNo}</div>` : ''}
      <div class="info-line">${t.address}: ${co.address || 'Lange Brink 15, 8315 AH Luttelgeest, Nederland'}</div>
      ${workingHoursStr ? `<div class="info-line"><strong>${t.workingHours}:</strong> ${workingHoursStr}</div>` : ''}
    </div>

    <div class="card">
      <div class="card-title">${t.toClient}</div>
      <div class="company-name">${invoice.client?.name || 'Client'}</div>
      <div class="info-line">${t.vatId}: ${invoice.client?.cui || '—'}</div>
      <div class="info-line">${t.address}: ${[invoice.client?.address, invoice.client?.postalCode, invoice.client?.country].filter(Boolean).join(', ') || '—'}</div>
      
      ${invoice.client?.contactEmail ? `<div class="info-line">${t.email}: ${invoice.client?.contactEmail}</div>` : ''}
      ${invoice.client?.phone ? `<div class="info-line">${t.phone}: ${invoice.client?.phone}</div>` : ''}
    </div>
  </div>

  <table class="service-table">
    <thead>
      <tr>
        <th>${t.description}</th>
        <th>${t.qty}</th>
        <th>${t.unitPrice}</th>
        <th>${t.amount}</th>
      </tr>
    </thead>
    <tbody>
      ${itemsHtml}
    </tbody>
  </table>

  <div class="main-bottom">

    <div class="section-box">
      <div class="section-title">${t.transportDetails}</div>

      ${(trip.pickupAddress || trip.dropoffAddress) ? `
      <div class="detail-row">
        <div class="detail-label">${t.route}</div>
        <div>${trip.pickupAddress || ''} - ${trip.dropoffAddress || ''}</div>
      </div>` : ''}

      ${trip.pickupDate ? `
      <div class="detail-row">
        <div class="detail-label">${t.pickupDate}</div>
        <div>${fmtDate(trip.pickupDate)}</div>
      </div>` : ''}

      ${trip.loadingReference ? `
      <div class="detail-row">
        <div class="detail-label">${t.loadingRef}</div>
        <div>${trip.loadingReference}</div>
      </div>` : ''}

      ${trip.dropoffDate ? `
      <div class="detail-row">
        <div class="detail-label">${t.deliveryDate}</div>
        <div>${fmtDate(trip.dropoffDate)}</div>
      </div>` : ''}

      ${trip.unloadingReference ? `
      <div class="detail-row">
        <div class="detail-label">${t.unloadingRef}</div>
        <div>${trip.unloadingReference}</div>
      </div>` : ''}

      ${cargoStr ? `
      <div class="detail-row">
        <div class="detail-label">${t.cargo}</div>
        <div>${cargoStr}</div>
      </div>` : ''}
    </div>

    <div class="section-box summary">
      <div class="summary-header">${t.summary}</div>

      <div class="summary-body">
        <div class="summary-row">
          <span>${t.subtotal}</span>
          <span>EUR ${subtotal.toFixed(2)}</span>
        </div>

        <div class="summary-row">
          <span>${vatLabel}</span>
          <span>EUR ${vatAmt.toFixed(2)}</span>
        </div>

        <div class="summary-line"></div>

        <div class="total-row">
          <span>${t.total}</span>
          <span class="total-amount">EUR ${finalTotal.toFixed(2)}</span>
        </div>

        <div class="vat-info">
          <strong>${t.vatInfo}</strong><br />
          The VAT rate applied is ${invoice.vatPercent || 19}%.<br />
          ${t.vatInfoText}
        </div>
      </div>
    </div>

  </div>

  <div class="payment-box">
    <div>
      <div class="section-title">${t.paymentInfo}</div>

      <div class="payment-table">
        <div><strong>${t.bank}:</strong> <span>${co.bank || 'ING'}</span></div>
        <div><strong>${t.iban}:</strong> <span>${co.iban || 'INGB 77 NL 5454 7475 7487 2454'}</span></div>
        <div><strong>${t.bic}:</strong> <span>${co.bic || 'INGBNL2A'}</span></div>
        <div><strong>${t.accHolder}:</strong> <span>${co.name || 'HapCargo BV'}</span></div>
      </div>
    </div>

    <div class="payment-note">
      <div>
        <strong>${t.lateWarning} ${termsStr}</strong><br />
        ${t.lateWarningSub}
      </div>
    </div>
  </div>

  <div class="footer">
    <div class="footer-contact">
      <span style="display:flex; align-items:center; gap:4px">
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>
        ${co.website || 'www.hapcargo.com'}
      </span>
      ${co.email ? `<span style="display:flex; align-items:center; gap:4px">
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>
        ${co.email}
      </span>` : ''}
      ${co.phone ? `<span style="display:flex; align-items:center; gap:4px">
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg>
        ${co.phone}
      </span>` : ''}
    </div>

    <div class="thank-you">${t.footer1}</div>
  </div>

</div>

</body>
</html>
`;
}
