import React from 'react';
import { getCompanySettings } from '../pages/SettingsPage';
import { Truck, Droplets, Receipt, Building, Phone, Mail, Landmark, User, MapPin, Calendar, Clock, FileText, AlertCircle, Info } from 'lucide-react';

interface Props {
  invoice: any;
  lang: 'en' | 'nl';
}

function fmtDate(dateStr: string | null | undefined): string {
  if (!dateStr) return '—';
  const d = new Date(dateStr);
  if (isNaN(d.getTime())) return '—';
  const dd = String(d.getDate()).padStart(2, '0');
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const yyyy = d.getFullYear();
  return `${dd}/${mm}/${yyyy}`;
}

export const InvoiceTemplate: React.FC<Props> = ({ invoice, lang }) => {
  const co = getCompanySettings();
  const trip = invoice.trip || {};

  const dict = {
    en: {
      invoice: 'INVOICE',
      invoiceNo: 'Invoice No:',
      tripRef: 'Trip Ref:',
      issueDate: 'Issue Date:',
      dueDate: 'Due Date:',
      from: 'FROM:',
      toClient: 'TO / CLIENT:',
      description: 'Description of Services',
      vat: 'VAT',
      qty: 'Qty',
      unitPrice: 'Unit Price (EUR)',
      amount: 'Amount (EUR)',
      serviceName: 'Road freight transport services',
      route: 'Route:',
      dates: 'Loading/Unloading:',
      cargo: 'Cargo:',
      pallets: 'Pallets',
      vehicle: 'Vehicle:',
      driver: 'Driver:',
      refs: 'Refs: Loading',
      unloading: 'Unloading',
      subtotal: 'Subtotal',
      total: 'TOTAL DUE',
      notes: 'Notes:',
      footer1: 'Thank you for your business!',
      footer2: 'Invoice automatically generated by HapCargo SaaS',
      taxId: 'Tax ID',
      regNo: 'Reg No',
      phone: 'Phone',
      email: 'Email',
      bank: 'Bank',
      iban: 'IBAN',
      bic: 'BIC / SWIFT',
      accHolder: 'Account Holder',
      vatId: 'VAT / Tax ID',
      paymentTerms: 'Payment Terms:',
      address: 'Address',
      pickupDate: 'Pickup date:',
      loadingRef: 'Loading reference:',
      deliveryDate: 'Delivery date:',
      unloadingRef: 'Unloading reference:',
      transportDetails: 'TRANSPORT DETAILS',
      summary: 'SUMMARY',
      vatInfo: 'VAT INFORMATION',
      vatInfoText: 'Thank you for your business!',
      paymentInfo: 'PAYMENT INFORMATION',
      lateWarning: 'Please make payment within',
      lateWarningSub: 'Late payments may incur additional charges.',
      draftTitle: 'DRAFT',
      draftSub: 'This is not a final invoice.'
    },
    nl: {
      invoice: 'FACTUUR',
      invoiceNo: 'Factuurnummer:',
      tripRef: 'Rit Ref:',
      issueDate: 'Factuurdatum:',
      dueDate: 'Vervaldatum:',
      from: 'VAN:',
      toClient: 'AAN / KLANT:',
      description: 'Omschrijving van diensten',
      vat: 'BTW',
      qty: 'Aantal',
      unitPrice: 'Eenheidsprijs (EUR)',
      amount: 'Bedrag (EUR)',
      serviceName: 'Wegtransportdiensten',
      route: 'Route:',
      dates: 'Laden/Lossen:',
      cargo: 'Lading:',
      pallets: 'Pallets',
      vehicle: 'Voertuig:',
      driver: 'Chauffeur:',
      refs: 'Ref: Laden',
      unloading: 'Lossen',
      subtotal: 'Subtotaal',
      total: 'TOTAAL TE BETALEN',
      notes: 'Notities:',
      footer1: 'Bedankt voor uw zaken!',
      footer2: 'Factuur automatisch gegenereerd door HapCargo SaaS',
      taxId: 'KVK / BTW',
      regNo: 'KVK',
      phone: 'Tel',
      email: 'E-mail',
      bank: 'Bank',
      iban: 'IBAN',
      bic: 'BIC / SWIFT',
      accHolder: 'Rekeninghouder',
      vatId: 'BTW / Tax ID',
      paymentTerms: 'Betalingsvoorwaarden:',
      address: 'Adres',
      pickupDate: 'Laaddatum:',
      loadingRef: 'Laadreferentie:',
      deliveryDate: 'Leverdatum:',
      unloadingRef: 'Losreferentie:',
      transportDetails: 'TRANSPORTGEGEVENS',
      summary: 'OVERZICHT',
      vatInfo: 'BTW INFORMATIE',
      vatInfoText: 'Bedankt voor uw zaken!',
      paymentInfo: 'BETALINGSINFORMATIE',
      lateWarning: 'Gelieve te betalen binnen',
      lateWarningSub: 'Te late betalingen kunnen leiden tot extra kosten.',
      draftTitle: 'CONCEPT',
      draftSub: 'Dit is geen definitieve factuur.'
    }
  };
  
  const t = (dict as any)[lang] || dict['en'];

  let termsStr = '30 days';
  if (invoice.issueDate && invoice.dueDate) {
    const diffTime = Math.abs(new Date(invoice.dueDate).getTime() - new Date(invoice.issueDate).getTime());
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
    termsStr = `${diffDays} days`;
  }

  const items = invoice.items || [];
  let itemsSubtotal = 0;
  if (items.length > 0) {
    items.forEach((item: any) => {
      itemsSubtotal += Number(item.total) || ((Number(item.quantity)||1) * (Number(item.unitPrice)||0));
    });
  } else {
    itemsSubtotal = Number(invoice.amount) || 0;
  }

  let subtotal = Number(invoice.subtotal) || itemsSubtotal;
  let vatLabel = `${t.vat} ${invoice.vatPercent || 19}%`;
  let vatAmt = Number(invoice.vatAmount) || (subtotal * (invoice.vatPercent || 19)) / 100;

  if (invoice.vatType === 'REVERSE_CHARGE') {
    vatLabel = `${t.vat} 0% (Reverse Charge)`;
    vatAmt = 0;
  } else if (invoice.vatType === 'EXEMPT') {
    vatLabel = `${t.vat} 0% (Exempt)`;
    vatAmt = 0;
  }
  const finalTotal = subtotal + vatAmt;

  const cargoArr = [];
  if (trip.pallets) cargoArr.push(`${trip.pallets} pallets`);
  if (trip.weightKg) cargoArr.push(`${trip.weightKg} kg`);
  if (trip.volumeCbm) cargoArr.push(`${trip.volumeCbm} m3`);
  const cargoStr = cargoArr.join(', ');

  const getIcon = (desc: string) => {
    const l = desc.toLowerCase();
    if (l.includes('transport')) return <Truck className="w-4 h-4 text-slate-800" />;
    if (l.includes('fuel')) return <Droplets className="w-4 h-4 text-slate-800" />;
    return <Receipt className="w-4 h-4 text-slate-800" />;
  };

  return (
    <div className="w-[794px] h-[1123px] bg-white text-slate-800 font-sans p-8 box-border overflow-hidden relative flex flex-col">
      
      {/* Header */}
      <div className="flex justify-between items-start mb-5">
        <div>
          {co.logoBase64 ? (
            <img src={co.logoBase64} alt="Logo" className="h-10 object-contain mb-3" />
          ) : (
            <div className="text-2xl font-bold text-orange-500 mb-3">{co.name || 'HapCargo BV'}</div>
          )}
          <h1 className="text-xl font-bold text-slate-900 tracking-wider">{t.invoice}</h1>
        </div>
        
        <div className="flex flex-col items-end gap-2">
          <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-[12px] text-right">
            <span className="font-semibold">{t.invoiceNo}</span>
            <span className={invoice.status === 'draft' ? 'text-orange-500 font-semibold' : 'text-slate-500'}>{invoice.invoiceNumber}</span>
            
            <span className="font-semibold">{t.issueDate}</span>
            <span className="text-slate-500">{fmtDate(invoice.issueDate)}</span>
            
            <span className="font-semibold">{t.dueDate}</span>
            <span className="text-slate-500">{fmtDate(invoice.dueDate)}</span>
            
            <span className="font-semibold">{t.paymentTerms}</span>
            <span className="text-slate-500">{termsStr}</span>

            {trip.referenceNumber && (
              <>
                <span className="font-semibold">{t.tripRef}</span>
                <span className="text-slate-500">{trip.referenceNumber}</span>
              </>
            )}
          </div>

          {invoice.status === 'draft' && (
            <div className="flex flex-col items-end mt-1">
              <div className="bg-slate-900 text-white px-3 py-1.5 rounded flex items-center gap-1.5 font-bold text-[12px]">
                <FileText className="w-3.5 h-3.5" />
                {t.draftTitle}
              </div>
              <span className="text-[10px] text-slate-500 mt-0.5">{t.draftSub}</span>
            </div>
          )}
        </div>
      </div>

      <hr className="border-t border-slate-200 mb-5" />

      {/* From / To */}
      <div className="grid grid-cols-2 gap-4 mb-5 shrink-0">
        {/* FROM */}
        <div className="border border-slate-200 rounded-lg p-4">
          <div className="flex items-center gap-1.5 text-orange-500 font-bold mb-3 text-[12px]">
            <Building className="w-4 h-4" />
            {t.from}
          </div>
          <div className="font-bold text-slate-900 mb-1.5 text-[12px]">{co.name || 'HapCargo BV'}</div>
          <div className="text-[11px] text-slate-500 space-y-0.5">
            <p>{t.taxId}: {co.cui || 'NL442452452145'}</p>
            {co.regNumber && <p>{t.regNo}: {co.regNumber}</p>}
            <p>{co.address || 'Lange Brink 15, 8315 AH Luttelgeest, Nederland'}</p>
            <div className="h-1.5"></div>
            {co.phone && <div className="flex items-center gap-1.5"><Phone className="w-3 h-3" /> {co.phone}</div>}
            {co.email && <div className="flex items-center gap-1.5"><Mail className="w-3 h-3" /> {co.email}</div>}
            {co.bank && <div className="flex items-center gap-1.5"><Landmark className="w-3 h-3" /> {t.bank}: {co.bank}</div>}
            {co.iban && <div className="font-bold text-slate-800">IBAN: {co.iban}</div>}
          </div>
        </div>

        {/* TO */}
        <div className="border border-slate-200 rounded-lg p-4">
          <div className="flex items-center gap-1.5 text-orange-500 font-bold mb-3 text-[12px]">
            <User className="w-4 h-4" />
            {t.toClient}
          </div>
          <div className="font-bold text-slate-900 mb-1.5 text-[12px]">{invoice.client?.name || 'Client'}</div>
          <div className="text-[11px] text-slate-500 space-y-0.5">
            <p>{t.vatId}: {invoice.client?.cui || '—'}</p>
            <p>{t.address}: {[invoice.client?.address, invoice.client?.postalCode, invoice.client?.country].filter(Boolean).join(', ') || '—'}</p>
            <div className="h-1.5"></div>
            {invoice.client?.contactEmail && <div className="flex items-center gap-1.5"><Mail className="w-3 h-3" /> {invoice.client.contactEmail}</div>}
            {invoice.client?.phone && <div className="flex items-center gap-1.5"><Phone className="w-3 h-3" /> {invoice.client.phone}</div>}
          </div>
        </div>
      </div>

      {/* Services Table */}
      <div className="mb-5 shrink-0">
        <div className="bg-slate-900 text-white rounded-t-lg px-4 py-2 grid grid-cols-12 font-bold text-[12px]">
          <div className="col-span-6">{t.description}</div>
          <div className="col-span-2 text-center">{t.qty}</div>
          <div className="col-span-2 text-center">{t.unitPrice}</div>
          <div className="col-span-2 text-right">{t.amount}</div>
        </div>
        <div className="border border-t-0 border-slate-200 rounded-b-lg">
          {items.length > 0 ? (
            items.map((item: any, i: number) => (
              <div key={i} className="px-4 py-2.5 grid grid-cols-12 items-center border-b border-slate-100 last:border-b-0 text-[12px]">
                <div className="col-span-6 flex items-center gap-2.5">
                  <div className="w-8 h-8 rounded-full bg-blue-50 flex items-center justify-center shrink-0">
                    {getIcon(item.description || '')}
                  </div>
                  <span className="font-medium text-slate-800 leading-tight">{item.description}</span>
                </div>
                <div className="col-span-2 text-center text-slate-500">{Number(item.quantity) || 1}</div>
                <div className="col-span-2 text-center text-slate-500">{(Number(item.unitPrice) || 0).toFixed(2)}</div>
                <div className="col-span-2 text-right font-bold text-slate-900">{((Number(item.quantity)||1)*(Number(item.unitPrice)||0)).toFixed(2)}</div>
              </div>
            ))
          ) : (
            <div className="px-4 py-2.5 grid grid-cols-12 items-center text-[12px]">
              <div className="col-span-6 flex items-center gap-2.5">
                <div className="w-8 h-8 rounded-full bg-blue-50 flex items-center justify-center shrink-0">
                  <Truck className="w-4 h-4 text-slate-800" />
                </div>
                <span className="font-medium text-slate-800">{t.serviceName}</span>
              </div>
              <div className="col-span-2 text-center text-slate-500">1</div>
              <div className="col-span-2 text-center text-slate-500">{(Number(invoice.amount)||0).toFixed(2)}</div>
              <div className="col-span-2 text-right font-bold text-slate-900">{(Number(invoice.amount)||0).toFixed(2)}</div>
            </div>
          )}
        </div>
      </div>

      {/* Details & Summary */}
      <div className="grid grid-cols-12 gap-4 mb-5 shrink-0">
        {/* Transport Details */}
        <div className="col-span-7 border border-slate-200 rounded-lg p-4">
          <div className="flex items-center gap-1.5 text-orange-500 font-bold mb-3 text-[12px]">
            <MapPin className="w-4 h-4" />
            {t.transportDetails}
          </div>
          <div className="text-[11px] space-y-2">
            {(trip.pickupAddress || trip.dropoffAddress) && (
              <div className="grid grid-cols-12 gap-2 border-b border-slate-100 pb-1.5">
                <div className="col-span-4 flex items-center gap-1.5 text-slate-600">
                  <MapPin className="w-3.5 h-3.5 text-slate-400 shrink-0" />
                  {t.route}
                </div>
                <div className="col-span-8 text-slate-900">{trip.pickupAddress || ''} - {trip.dropoffAddress || ''}</div>
              </div>
            )}
            <div className="grid grid-cols-12 gap-2 border-b border-slate-100 pb-1.5">
              <div className="col-span-4 flex items-center gap-1.5 text-slate-600">
                <Calendar className="w-3.5 h-3.5 text-slate-400 shrink-0" />
                {t.pickupDate}
              </div>
              <div className="col-span-8 text-slate-900">{fmtDate(trip.pickupDate)}</div>
            </div>
            {trip.loadingReference && (
              <div className="grid grid-cols-12 gap-2 border-b border-slate-100 pb-1.5">
                <div className="col-span-4 flex items-center gap-1.5 text-slate-600">
                  <FileText className="w-3.5 h-3.5 text-slate-400 shrink-0" />
                  {t.loadingRef}
                </div>
                <div className="col-span-8 text-slate-900">{trip.loadingReference}</div>
              </div>
            )}
            <div className="grid grid-cols-12 gap-2 border-b border-slate-100 pb-1.5">
              <div className="col-span-4 flex items-center gap-1.5 text-slate-600">
                <Clock className="w-3.5 h-3.5 text-slate-400 shrink-0" />
                {t.deliveryDate}
              </div>
              <div className="col-span-8 text-slate-900">{fmtDate(trip.dropoffDate)}</div>
            </div>
            {trip.unloadingReference && (
              <div className="grid grid-cols-12 gap-2 border-b border-slate-100 pb-1.5">
                <div className="col-span-4 flex items-center gap-1.5 text-slate-600">
                  <FileText className="w-3.5 h-3.5 text-slate-400 shrink-0" />
                  {t.unloadingRef}
                </div>
                <div className="col-span-8 text-slate-900">{trip.unloadingReference}</div>
              </div>
            )}
            {cargoStr && (
              <div className="grid grid-cols-12 gap-2">
                <div className="col-span-4 flex items-center gap-1.5 text-slate-600">
                  <Receipt className="w-3.5 h-3.5 text-slate-400 shrink-0" />
                  {t.cargo}
                </div>
                <div className="col-span-8 text-slate-900">{cargoStr}</div>
              </div>
            )}
          </div>
        </div>

        {/* Summary */}
        <div className="col-span-5 border border-slate-200 rounded-lg flex flex-col">
          <div className="bg-slate-900 text-white px-4 py-2 rounded-t-lg font-bold text-[12px]">
            {t.summary}
          </div>
          <div className="p-4 flex flex-col justify-between flex-1">
            <div>
              <div className="flex justify-between text-[12px] mb-2.5">
                <span className="text-slate-600">{t.subtotal}</span>
                <span className="text-slate-900">EUR {subtotal.toFixed(2)}</span>
              </div>
              <div className="flex justify-between text-[12px] mb-3 border-b border-slate-200 pb-3">
                <span className="text-slate-600">{vatLabel}</span>
                <span className="text-slate-900">EUR {vatAmt.toFixed(2)}</span>
              </div>
              <div className="flex justify-between items-center mb-4">
                <span className="font-bold text-slate-900 text-[12px]">{t.total}</span>
                <span className="text-lg font-bold text-orange-500">EUR {finalTotal.toFixed(2)}</span>
              </div>
            </div>

            <div className="bg-blue-50 rounded p-2.5 text-[10px]">
              <div className="flex items-center gap-1 font-bold text-slate-800 mb-0.5">
                <Info className="w-3.5 h-3.5 text-slate-600 shrink-0" />
                {t.vatInfo}
              </div>
              <p className="text-slate-600">The VAT rate applied is {invoice.vatPercent || 19}%.</p>
              <p className="text-slate-600">{t.vatInfoText}</p>
            </div>
          </div>
        </div>
      </div>

      {/* Payment Info */}
      <div className="border border-slate-200 rounded-lg p-4 flex shrink-0">
        <div className="flex-1 border-r border-slate-100 pr-4">
          <div className="flex items-center gap-1.5 text-orange-500 font-bold mb-3 text-[12px]">
            <Landmark className="w-4 h-4" />
            {t.paymentInfo}
          </div>
          <div className="grid grid-cols-12 gap-x-2 gap-y-1 text-[11px]">
            <div className="col-span-3 text-slate-500">{t.bank}:</div>
            <div className="col-span-9 text-slate-900">{co.bank || 'ING'}</div>
            
            <div className="col-span-3 text-slate-500">{t.iban}:</div>
            <div className="col-span-9 font-bold text-slate-900">{co.iban || 'INGB 77 NL 5454 7475 7487 2454'}</div>
            
            <div className="col-span-3 text-slate-500">{t.bic}:</div>
            <div className="col-span-9 text-slate-900">{co.bic || 'INGBNL2A'}</div>
            
            <div className="col-span-3 text-slate-500">{t.accHolder}:</div>
            <div className="col-span-9 text-slate-900">{co.name || 'HapCargo BV'}</div>
          </div>
        </div>
        
        <div className="flex-1 pl-4 flex items-center justify-center">
          <div className="flex items-start gap-2.5">
            <AlertCircle className="w-5 h-5 text-slate-600 shrink-0" />
            <div>
              <div className="font-bold text-slate-900 text-[12px]">{t.lateWarning} {termsStr}</div>
              <div className="text-[10px] text-slate-500 mt-0.5">{t.lateWarningSub}</div>
            </div>
          </div>
        </div>
      </div>

      {/* Spacer to push footer to bottom if needed, though absolute positioning works if height is constrained */}
      <div className="flex-1"></div>

      {/* Footer */}
      <div className="mt-4 shrink-0">
        <div className="flex justify-center items-center gap-3 text-[11px] text-slate-500 mb-1.5">
          {co.website && <span className="flex items-center gap-1"><Globe className="w-3 h-3" /> {co.website}</span>}
          {co.website && co.email && <span className="text-slate-300">|</span>}
          {co.email && <span className="flex items-center gap-1"><Mail className="w-3 h-3" /> {co.email}</span>}
          {co.email && co.phone && <span className="text-slate-300">|</span>}
          {co.phone && <span className="flex items-center gap-1"><Phone className="w-3 h-3" /> {co.phone}</span>}
        </div>
        <div className="text-center italic text-slate-600 text-[11px] font-bold">{t.footer1}</div>
      </div>
    </div>
  );
};

function Globe(props: any) {
  return (
    <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <circle cx="12" cy="12" r="10"/>
      <line x1="2" y1="12" x2="22" y2="12"/>
      <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/>
    </svg>
  );
}
