$ErrorActionPreference = 'Stop'
$path = Join-Path $PSScriptRoot "..\Saas HapTrans\client\src\lib\i18n.ts"
$content = [System.IO.File]::ReadAllText($path)

$langBlocks = @(
@'
ai_import_hint_excel: "Încarcă o confirmare de tarif, CMR, ordin de transport sau fișier Excel/CSV (poate conține mai multe curse). AI-ul extrage datele și creează comenzile.",
ai_pick_file_excel: "PDF, imagine sau Excel/CSV",
ai_pick_file_sub: "Fișierele cu mai multe curse sunt detectate automat",
ai_no_trips: "Nu s-au găsit date de cursă în document. Încearcă alt fișier.",
ai_trips_found: "{{count}} curse detectate — verifică înainte de import",
ai_select_all: "Selectează toate",
ai_deselect_all: "Deselectează toate",
ai_trip_n: "Curşa {{n}}",
ai_route_unknown: "Necunoscut",
ai_toggle_trip: "Selectează cursa",
ai_f_pickup_addr: "Încărcare",
ai_f_dropoff_addr: "Descărcare",
ai_f_pickup_date: "Data încărcării",
ai_f_dropoff_date: "Data descărcării",
ai_f_price: "Preț",
ai_f_weight: "Greutate",
ai_f_pallets: "Palet",
ai_f_volume: "Volum",
ai_f_distance: "Distanță",
ai_f_loading_ref: "Ref. încărcare",
ai_f_unloading_ref: "Ref. descărcare",
ai_f_customer_ref: "Ref. client",
ai_f_contact: "Contact",
ai_f_notes: "Note",
ai_client_section: "Client (comanditor)",
ai_c_vat: "Cod TVA",
ai_c_address: "Adresă",
ai_c_email: "Email",
ai_c_phone: "Telefon",
ai_client_will_create: "Client nou — va fi creat automat la import",
ai_import_confirm_one: "Creează comanda",
ai_import_confirm_multi: "Creează {{count}} comenzi",
ai_imported_multi: "{{count}} comenzi create din document!",
'@
@'
ai_import_hint_excel: "Importez une confirmation de tarif, CMR, ordre de transport ou fichier Excel/CSV (peut contenir plusieurs tournées). L'IA extrait les données et crée les commandes.",
ai_pick_file_excel: "PDF, image ou Excel/CSV",
ai_pick_file_sub: "Les fichiers avec plusieurs tournées sont détectés automatiquement",
ai_no_trips: "Aucune donnée de tournée trouvée dans le document. Essayez un autre fichier.",
ai_trips_found: "{{count}} tournées détectées — vérifiez avant import",
ai_select_all: "Tout sélectionner",
ai_deselect_all: "Tout désélectionner",
ai_trip_n: "Tournée {{n}}",
ai_route_unknown: "Inconnu",
ai_toggle_trip: "Sélectionner la tournée",
ai_f_pickup_addr: "Chargement",
ai_f_dropoff_addr: "Livraison",
ai_f_pickup_date: "Date de chargement",
ai_f_dropoff_date: "Date de livraison",
ai_f_price: "Prix",
ai_f_weight: "Poids",
ai_f_pallets: "Palettes",
ai_f_volume: "Volume",
ai_f_distance: "Distance",
ai_f_loading_ref: "Réf. chargement",
ai_f_unloading_ref: "Réf. livraison",
ai_f_customer_ref: "Réf. client",
ai_f_contact: "Contact",
ai_f_notes: "Remarques",
ai_client_section: "Client (donneur d'ordre)",
ai_c_vat: "N° TVA",
ai_c_address: "Adresse",
ai_c_email: "E-mail",
ai_c_phone: "Téléphone",
ai_client_will_create: "Nouveau client — sera créé automatiquement lors de l'import",
ai_import_confirm_one: "Créer la commande",
ai_import_confirm_multi: "Créer {{count}} commandes",
ai_imported_multi: "{{count}} commandes créées depuis le document !",
'@
@'
ai_import_hint_excel: "Upload a rate confirmation, CMR, transport order or Excel/CSV file (it may contain multiple trips). AI extracts the data and creates the orders.",
ai_pick_file_excel: "PDF, image or Excel/CSV",
ai_pick_file_sub: "Files containing multiple trips are detected automatically",
ai_no_trips: "No trip data found in the document. Try another file.",
ai_trips_found: "{{count}} trips detected — review before import",
ai_select_all: "Select all",
ai_deselect_all: "Deselect all",
ai_trip_n: "Trip {{n}}",
ai_route_unknown: "Unknown",
ai_toggle_trip: "Toggle trip selection",
ai_f_pickup_addr: "Loading",
ai_f_dropoff_addr: "Delivery",
ai_f_pickup_date: "Loading date",
ai_f_dropoff_date: "Delivery date",
ai_f_price: "Price",
ai_f_weight: "Weight",
ai_f_pallets: "Pallets",
ai_f_volume: "Volume",
ai_f_distance: "Distance",
ai_f_loading_ref: "Loading ref",
ai_f_unloading_ref: "Unloading ref",
ai_f_customer_ref: "Customer ref",
ai_f_contact: "Contact",
ai_f_notes: "Notes",
ai_client_section: "Client (ordering party)",
ai_c_vat: "VAT number",
ai_c_address: "Address",
ai_c_email: "Email",
ai_c_phone: "Phone",
ai_client_will_create: "New client — will be created automatically on import",
ai_import_confirm_one: "Create order",
ai_import_confirm_multi: "Create {{count}} orders",
ai_imported_multi: "{{count}} orders created from document!",
'@
@'
ai_import_hint_excel: "Upload een tariefbevestiging, CMR, transportopdracht of Excel/CSV-bestand (kan meerdere rritten bevatten). AI haalt de gegevens eruit en maakt de opdrachten aan.",
ai_pick_file_excel: "PDF, afbeelding of Excel/CSV",
ai_pick_file_sub: "Bestanden met meerdere ritten worden automatisch gedetecteerd",
ai_no_trips: "Geen ritgegevens gevonden in het document. Probeer een ander bestand.",
ai_trips_found: "{{count}} ritten gedetecteerd — controleer vóór import",
ai_select_all: "Alles selecteren",
ai_deselect_all: "Alles deselecteren",
ai_trip_n: "Rit {{n}}",
ai_route_unknown: "Onbekend",
ai_toggle_trip: "Rit selecteren",
ai_f_pickup_addr: "Laden",
ai_f_dropoff_addr: "Lossen",
ai_f_pickup_date: "Laaddatum",
ai_f_dropoff_date: "Losdatum",
ai_f_price: "Prijs",
ai_f_weight: "Gewicht",
ai_f_pallets: "Pallets",
ai_f_volume: "Volume",
ai_f_distance: "Afstand",
ai_f_loading_ref: "Ref. laden",
ai_f_unloading_ref: "Ref. lossen",
ai_f_customer_ref: "Klantreferentie",
ai_f_contact: "Contact",
ai_f_notes: "Opmerkingen",
ai_client_section: "Klant (opdrachtgever)",
ai_c_vat: "BTW-nummer",
ai_c_address: "Adres",
ai_c_email: "E-mail",
ai_c_phone: "Telefoon",
ai_client_will_create: "Nieuwe klant — wordt automatisch aangemaakt bij import",
ai_import_confirm_one: "Opdracht maken",
ai_import_confirm_multi: "{{count}} opdrachten maken",
ai_imported_multi: "{{count}} opdrachten aangemaakt vanuit document!",
'@
@'
ai_import_hint_excel: "Lade eine Tarifbestätigung, einen CMR, Transportauftrag oder eine Excel-/CSV-Datei hoch (kann mehrere Fahrten enthalten). Die KI extrahiert die Daten und erstellt die Aufträge.",
ai_pick_file_excel: "PDF, Bild oder Excel/CSV",
ai_pick_file_sub: "Dateien mit mehreren Fahrten werden automatisch erkannt",
ai_no_trips: "Keine Fahrtdaten im Dokument gefunden. Versuche eine andere Datei.",
ai_trips_found: "{{count}} Fahrten erkannt — vor dem Import prüfen",
ai_select_all: "Alle auswählen",
ai_deselect_all: "Alle abwählen",
ai_trip_n: "Fahrt {{n}}",
ai_route_unknown: "Unbekannt",
ai_toggle_trip: "Fahrt auswählen",
ai_f_pickup_addr: "Verladung",
ai_f_dropoff_addr: "Entladung",
ai_f_pickup_date: "Verladedatum",
ai_f_dropoff_date: "Lieferdatum",
ai_f_price: "Preis",
ai_f_weight: "Gewicht",
ai_f_pallets: "Paletten",
ai_f_volume: "Volumen",
ai_f_distance: "Entfernung",
ai_f_loading_ref: "Ref. Verladung",
ai_f_unloading_ref: "Ref. Entladung",
ai_f_customer_ref: "Kundenreferenz",
ai_f_contact: "Kontakt",
ai_f_notes: "Notizen",
ai_client_section: "Kunde (Auftraggeber)",
ai_c_vat: "USt-IdNr.",
ai_c_address: "Adresse",
ai_c_email: "E-Mail",
ai_c_phone: "Telefon",
ai_client_will_create: "Neuer Kunde — wird beim Import automatisch erstellt",
ai_import_confirm_one: "Auftrag erstellen",
ai_import_confirm_multi: "{{count}} Aufträge erstellen",
ai_imported_multi: "{{count}} Aufträge aus dem Dokument erstellt!",
'@
)

$pattern = '(?m)^([ \t]*)ai_import_failed:.*?\r?\n'
$ms = [regex]::Matches($content, $pattern)
if ($ms.Count -ne 5) { throw "Expected 5 'ai_import_failed' anchors (ro,fr,en,nl,de), found $($ms.Count)" }

for ($i = $ms.Count - 1; $i -ge 0; $i--) {
    $indent = $ms[$i].Groups[1].Value
    $lines = ($langBlocks[$i] -split "`n") | Where-Object { $_.Trim() } | ForEach-Object { $indent + $_.TrimEnd() }
    $block = (($lines -join "`r`n")) + "`r`n"
    $pos = $ms[$i].Index + $ms[$i].Length
    $content = $content.Substring(0, $pos) + $block + $content.Substring($pos)
}

[System.IO.File]::WriteAllText($path, $content, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Inserted AI-import keys into $($ms.Count) languages."
