/**
 * Tailwind design-token preset shared across web apps and portals.
 * Plain ES module (no TS-only syntax) so it can be consumed from both
 * tailwind.config.ts and tailwind.config.js without typecheck issues.
 *
 * @type {import('tailwindcss').Config}
 */
export default {
  darkMode: ['class'],
  content: [],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: 'hsl(var(--card))',
        'card-foreground': 'hsl(var(--card-foreground))',
        popover: 'hsl(var(--popover))',
        'popover-foreground': 'hsl(var(--popover-foreground))',
        primary: 'hsl(var(--primary))',
        'primary-foreground': 'hsl(var(--primary-foreground))',
        'primary-hover': 'hsl(var(--primary-hover))',
        'primary-muted': 'hsl(var(--primary-muted))',
        secondary: 'hsl(var(--secondary))',
        'secondary-foreground': 'hsl(var(--secondary-foreground))',
        'secondary-hover': 'hsl(var(--secondary-hover))',
        muted: 'hsl(var(--muted))',
        'muted-foreground': 'hsl(var(--muted-foreground))',
        accent: 'hsl(var(--accent))',
        'accent-foreground': 'hsl(var(--accent-foreground))',
        destructive: 'hsl(var(--destructive))',
        'destructive-foreground': 'hsl(var(--destructive-foreground))',
        'destructive-muted': 'hsl(var(--destructive-muted))',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        'ring-offset': 'hsl(var(--ring-offset))',
        success: 'hsl(var(--success))',
        'success-foreground': 'hsl(var(--success-foreground))',
        'success-muted': 'hsl(var(--success-muted))',
        warning: 'hsl(var(--warning))',
        'warning-foreground': 'hsl(var(--warning-foreground))',
        'warning-muted': 'hsl(var(--warning-muted))',
        info: 'hsl(var(--info))',
        'info-foreground': 'hsl(var(--info-foreground))',
        'info-muted': 'hsl(var(--info-muted))',
        /* Operational status colors */
        'status-planned': 'hsl(var(--status-planned))',
        'status-planned-muted': 'hsl(var(--status-planned-muted))',
        'status-assigned': 'hsl(var(--status-assigned))',
        'status-assigned-muted': 'hsl(var(--status-assigned-muted))',
        'status-confirmed': 'hsl(var(--status-confirmed))',
        'status-confirmed-muted': 'hsl(var(--status-confirmed-muted))',
        'status-dispatched': 'hsl(var(--status-dispatched))',
        'status-dispatched-muted': 'hsl(var(--status-dispatched-muted))',
        'status-active': 'hsl(var(--status-active))',
        'status-active-muted': 'hsl(var(--status-active-muted))',
        'status-on-time': 'hsl(var(--status-on-time))',
        'status-on-time-muted': 'hsl(var(--status-on-time-muted))',
        'status-at-risk': 'hsl(var(--status-at-risk))',
        'status-at-risk-muted': 'hsl(var(--status-at-risk-muted))',
        'status-delayed': 'hsl(var(--status-delayed))',
        'status-delayed-muted': 'hsl(var(--status-delayed-muted))',
        'status-completed': 'hsl(var(--status-completed))',
        'status-completed-muted': 'hsl(var(--status-completed-muted))',
        'status-cancelled': 'hsl(var(--status-cancelled))',
        'status-cancelled-muted': 'hsl(var(--status-cancelled-muted))',
        'status-offline': 'hsl(var(--status-offline))',
        'status-offline-muted': 'hsl(var(--status-offline-muted))',
        'status-available': 'hsl(var(--status-available))',
        'status-available-muted': 'hsl(var(--status-available-muted))',
        'status-exception': 'hsl(var(--status-exception))',
        'status-exception-muted': 'hsl(var(--status-exception-muted))',
        'status-pending': 'hsl(var(--status-pending))',
        'status-pending-muted': 'hsl(var(--status-pending-muted))',
        'status-approved': 'hsl(var(--status-approved))',
        'status-approved-muted': 'hsl(var(--status-approved-muted))',
        'status-rejected': 'hsl(var(--status-rejected))',
        'status-rejected-muted': 'hsl(var(--status-rejected-muted))',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius)',
        md: 'calc(var(--radius) + 2px)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        xs: ['var(--text-xs)', { lineHeight: 'var(--leading-normal)' }],
        sm: ['var(--text-sm)', { lineHeight: 'var(--leading-normal)' }],
        base: ['var(--text-base)', { lineHeight: 'var(--leading-normal)' }],
        lg: ['var(--text-lg)', { lineHeight: 'var(--leading-snug)' }],
        xl: ['var(--text-xl)', { lineHeight: 'var(--leading-snug)' }],
        '2xl': ['var(--text-2xl)', { lineHeight: 'var(--leading-tight)' }],
        '3xl': ['var(--text-3xl)', { lineHeight: 'var(--leading-tight)' }],
        '4xl': ['var(--text-4xl)', { lineHeight: 'var(--leading-tight)' }],
      },
      fontWeight: {
        normal: 'var(--font-normal)',
        medium: 'var(--font-medium)',
        semibold: 'var(--font-semibold)',
        bold: 'var(--font-bold)',
      },
      lineHeight: {
        tight: 'var(--leading-tight)',
        snug: 'var(--leading-snug)',
        normal: 'var(--leading-normal)',
        relaxed: 'var(--leading-relaxed)',
      },
      spacing: {
        0: 'var(--space-0)',
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '200ms',
        slow: '300ms',
      },
      transitionTimingFunction: {
        ease: 'ease',
      },
      zIndex: {
        dropdown: '100',
        sticky: '200',
        modal: '300',
        popover: '400',
        tooltip: '500',
        toast: '600',
      },
      width: {
        sidebar: 'var(--sidebar-width)',
        'sidebar-collapsed': 'var(--sidebar-collapsed-width)',
      },
      height: {
        topbar: 'var(--topbar-height)',
      },
      maxWidth: {
        content: 'var(--content-max-width)',
      },
    },
    container: {
      center: true,
      padding: 'var(--content-padding)',
      screens: {
        '2xl': '1440px',
      },
    },
  },
};
